app/urls.py
from django.urls import path

from app.views import setting, students, years, school, promotion, branch, enrollment, grades

urlpatterns = [
    path('settings/', setting.settings, name='settings'),
    path('students/', students.StudentsListView.as_view(), name='student-list'),
    path('students/actives/', students.ActiveStudentsListView.as_view(), name='student-actives'),
    path('students/actives/add/', students.add_student, name='add-new-student'),
    path('students/actives/<str:id>/update/', students.update_student, name='update-student'),
    path('students/olds/', students.OldStudentsListView.as_view(), name='student-old'),
    path('students/olds/add/', students.add_old, name='add-old-student'),
    # path('students/save-new/', students.dropzone_image, name='save-new-student'),
    path('students/<str:id>/', students.detail_student, name='student-details'),

    path('years/', years.list, name='year-list'),
    path('years/create', years.create, name='create-year'),
    path('years/<str:id>/update/', years.update, name="update-year"),

    path('promotions/create', promotion.create, name='create-promo'),
    path('promotions/<str:id>/update/', promotion.update, name="update-promo"),

    path('schools/create', school.create, name='create-school'),
    path('schools/<str:id>/update/', school.update, name="update-school"),

    path('branches/create', branch.create, name='create-branch'),
    path('branches/<str:id>/update/', branch.update, name="update-branch"),

    path('enrollments/news/', enrollment.newEnrollments, name='new-enrollments'),
    path('enrollments/news/add/', enrollment.add_active, name='add-active'),
    path('enrollments/news/<str:id>/update/', enrollment.update_active, name='update-active'),
    path('enrollments/olds/', enrollment.oldEnrollments, name='old-enrollments'),
    path('enrollments/olds/add/', enrollment.add_old, name='add-old-enr'),
    path('enrollments/olds/<str:id>/update/', enrollment.update_old, name='update-old-enr'),

    path('results/news/', grades.newGrades, name='new-grades'),
    # path('grades/news/<str:id>/', enrollment.add_active_grade, name='create-active-grade'),
    path('results/olds/', grades.oldGrades, name='old-grades'),

    path('save_grade/', enrollment.save_grade, name='save_grade'),
    path('save_grade_old/', enrollment.save_grade_old, name='save_grade_old'),

]

auth_app/urls.py
from django.urls import path

from auth_app.views import *

app_name = 'auth'
urlpatterns = [
    path('signin/', signin, name='signin'),
    path('logout/', custom_logout, name='logout'),
    path('signup/', signup, name='signup'),
    path('profile/', profile, name='profile'),
    path('lock/', lock, name='lock'),
]

iskane/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from .views import index

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', index, name='index'),
    path('', include('app.urls')),
    path('auth/', include('auth_app.urls')),
]
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/users/lock.html
{% extends 'users/base.html' %}
{% block content %}
    <div class="col mx-auto">
        <div class="auth-form-box">
            <div class="text-center mb-5">
                <div class="avatar avatar-4xl mb-4">
                    <img class="rounded-circle" src="../../../assets/img/team/30.webp"
                                                         alt=""/>
                </div>
                <h2 class="text-body-highlight"><span class="fw-normal">Hello </span>John Smith</h2>
                <p class="text-body-tertiary">Enter your password to access <br
                        class="d-sm-none d-md-block d-xxl-none"/>the admin</p>
            </div>
            <input class="form-control mb-3" id="password" type="password" placeholder="Enter Password"/><a
                class="btn btn-primary w-100" href="../../../index.html">Sign In</a>
        </div>
    </div>
{% endblock %}

templates/users/profile.html
{% extends 'layouts/_base.html' %}
{% load static %}
{% load widget_tweaks %}
{% block title %}
    Profile
{% endblock %}
{% block content %}
    <div class="mb-9">
        <div class="row g-6">
            <div class="col-12 col-xl-4">
                <div class="card mb-5">
                    <div class="card-header hover-actions-trigger position-relative mb-6" style="min-height: 130px; ">
                        <div class="bg-holder rounded-top"
                             style="background-image: linear-gradient(0deg, #000000 -3%, rgba(0, 0, 0, 0) 83%), url({% static 'assets/img/generic/59.png' %})">
                            <label
                                    class="cover-image-file-input" for="upload-settings-cover-image"></label>
                            <div class="hover-actions end-0 bottom-0 pe-1 pb-2 text-white dark__text-gray-1100"><span
                                    class="fa-solid fa-camera me-2"></span></div>
                        </div>
                        <label
                                class="avatar avatar-4xl status-online feed-avatar-profile cursor-pointer"
                                for="upload-settings-porfile-picture"><img
                                class="rounded-circle img-thumbnail shadow-sm border-0"
                                src="{{ request.user.profile_pic.url }}"
                                width="200" alt=""/></label>
                    </div>
                    <div class="card-body">
                        <div class="row">
                            <div class="col-12">
                                <div class="d-flex flex-wrap mb-2 align-items-center">
                                    <h3 class="me-2">{{ request.user.first_name }} {{ request.user.last_name }} </h3>
                                    <span class="fw-normal fs-8">u/{{ request.user }}</span>
                                </div>
                                <div class="d-flex d-xl-block d-xxl-flex align-items-center">
                                    <div class="d-flex mb-xl-2 mb-xxl-0"><span
                                            class="fa-solid fa-envelope fs-10 me-2 me-lg-1 me-xl-2"></span>
                                        <h6 class="d-inline-block mb-0">{{ request.user.email }}
                                        </h6>
                                    </div>
                                    <div class="d-flex"><span
                                            class="fa-solid fa-phone fs-10 me-2 me-lg-1 me-xl-2"></span>
                                        <h6 class="d-block d-xl-inline-block mb-0">{{ request.user.telephone }}
                                        </h6>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>

            </div>
            <div class="col-12 col-xl-8">
                <div class="mb-2">
                    <div class="mb-6">
                        <h4 class="mb-4"> Information Personnelle</h4>
                        <form action="" id="profile-form" method="post">
                            <div class="row g-3">
                                <div class="col-12 col-sm-6">
                                    <div class="form-icon-container">
                                        <div class="form-floating">
                                            {% render_field user_form.first_name class="form-control form-icon-input" %}
                                            {#                                        <input class="form-control form-icon-input"#}
                                            {#                                                                      id="firstName" type="text"#}
                                            {#                                                                      placeholder="First Name"/>#}
                                            <label
                                                    class="text-body-tertiary form-icon-label" for="firstName">FIRST
                                                NAME</label></div>
                                        <span class="fa-solid fa-user text-body fs-9 form-icon"></span>
                                    </div>
                                </div>
                                <div class="col-12 col-sm-6">
                                    <div class="form-icon-container">
                                        <div class="form-floating">
                                            {% render_field user_form.last_name class="form-control form-icon-input" %}
                                            {#                                        <input class="form-control form-icon-input" id="lastName"#}
                                            {#                                                                      type="text" placeholder="Last Name"/>#}
                                            <label
                                                    class="text-body-tertiary form-icon-label" for="lastName">LAST
                                                NAME</label>
                                        </div>
                                        <span class="fa-solid fa-user text-body fs-9 form-icon"></span>
                                    </div>
                                </div>
                                <div class="col-12 col-sm-6">
                                    <div class="form-icon-container">
                                        <div class="form-floating">
                                            {% render_field user_form.email class="form-control form-icon-input" %}
                                            {#                                        <input class="form-control form-icon-input"#}
                                            {#                                                                      id="emailSocial" type="email"#}
                                            {#                                                                      placeholder="Email"/>#}
                                            <label
                                                    class="text-body-tertiary form-icon-label" for="emailSocial">ENTER
                                                YOUR
                                                EMAIL</label></div>
                                        <span class="fa-solid fa-envelope text-body fs-9 form-icon"></span>
                                    </div>
                                </div>
                                <div class="col-12 col-sm-6">
                                    <div class="form-icon-container">
                                        <div class="form-floating">
                                            {#                                        <input class="form-control form-icon-input" id="phone"#}
                                            {#                                                                      type="tel" placeholder="Phone"/>#}
                                            {% render_field user_form.telephone class="form-control form-icon-input" %}
                                            <label
                                                    class="text-body-tertiary form-icon-label" for="phone">ENTER YOUR
                                                PHONE</label></div>
                                        <span class="fa-solid fa-phone text-body fs-9 form-icon"></span>
                                    </div>
                                </div>
                            </div>
                            <div class="text-end mb-6 mt-4">
                                <div>
                                    <button class="btn btn-phoenix-primary">Enregistrer</button>
                                </div>
                            </div>
                        </form>
                    </div>
                    <div class="row gx-3 mb-6 gy-6 gy-sm-3">
                        <div class="col-12 col-sm-6">
                            <h4 class="mb-4">Changer Mot de Passe</h4>
                            <form action="" id="password-form" method="post">
                                <div class="form-icon-container mb-3">
                                    <div class="form-floating"><input class="form-control form-icon-input"
                                                                      id="oldPassword"
                                                                      type="password" placeholder="Old password"/><label
                                            class="text-body-tertiary form-icon-label" for="oldPassword">Old
                                        Password</label></div>
                                    <span class="fa-solid fa-lock text-body fs-9 form-icon"></span>
                                </div>
                                <div class="form-icon-container mb-3">
                                    <div class="form-floating"><input class="form-control form-icon-input"
                                                                      id="newPassword"
                                                                      type="password" placeholder="New password"/><label
                                            class="text-body-tertiary form-icon-label" for="newPassword">New
                                        Password</label></div>
                                    <span class="fa-solid fa-key text-body fs-9 form-icon"></span>
                                </div>
                                <div class="form-icon-container">
                                    <div class="form-floating"><input class="form-control form-icon-input"
                                                                      id="newPassword2"
                                                                      type="password"
                                                                      placeholder="Confirm New password"/><label
                                            class="text-body-tertiary form-icon-label" for="newPassword2">Confirm New
                                        Password</label></div>
                                    <span class="fa-solid fa-key text-body fs-9 form-icon"></span>
                                </div>
                                <div class="text-end mb-3 mt-4">
                                    <div>
                                        <button class="btn btn-phoenix-primary">Enregistrer</button>
                                    </div>
                                </div>
                            </form>
                        </div>
                    </div>
                </div>

            </div>
        </div>
    </div>
{% endblock %}
{% block scripts %}
    <script>

    </script>
{% endblock %}

templates/users/signin.html
{% extends 'users/base.html' %}
{% load static %}
{% load widget_tweaks %}
{% block content %}
    <div class="col mx-auto">
        <div class="auth-form-box">
            <div class="text-center mb-7"><a class="d-flex flex-center text-decoration-none mb-4"
                                             href="{% url 'index' %}">
                <div class="d-flex align-items-center fw-bolder fs-3 d-inline-block"><img
                        src="{% static '/assets/img/icons/logo-iskane.png' %}" alt="phoenix" width="100"/></div>
            </a>
                <h3 class="text-body-highlight">Connexion</h3>
                <p class="text-body-tertiary">Accédez à votre compte</p>
            </div>
            <form method="post" action="">
                {% csrf_token %}
                <div class="mb-3 text-start"><label class="form-label" for="username">Adresse mail ou nom
                    d'utilisateur</label>
                    <div class="form-icon-container">
                        {% render_field form.username class="form-control form-icon-input" %}
                        {#                        <input class="form-control form-icon-input" id="username" name="username" type="email" placeholder="name@example.com"/>#}
                        <span class="fas fa-user text-body fs-9 form-icon"></span>
                    </div>
                </div>
                <div class="mb-3 text-start"><label class="form-label" for="password">Mot de passe</label>
                    <div class="form-icon-container">
                        {% render_field form.password class="form-control form-icon-input" %}
                        {#                        <input class="form-control form-icon-input" id="password" type="password" placeholder="Password"/>#}
                        <span class="fas fa-key text-body fs-9 form-icon"></span>
                    </div>
                </div>
                <div class="row flex-between-center mb-4">
                     <div class="col-auto">
                      <!--  <div class="form-check mb-0">
                            <input class="form-check-input" id="basic-checkbox" type="checkbox" checked="checked"/>
                            <label class="form-check-label mb-0" for="basic-checkbox">Remember me </label>
                        </div>-->
                    </div>
                    <div class="col-auto"><a class="fs-9 fw-semibold" href="#">Mot de passe oublié ?</a></div>
                </div>
                <button type="submit" class="btn btn-primary w-100 mb-3">Connexion</button>
                <div class="text-center">Vous n'avez pas un compte ?
                    <a class="fs-9 fw-bold" href="{% url 'auth:signup' %}">Créez-en</a>
                </div>
            </form>
        </div>
    </div>
{% endblock %}

templates/users/signup.html
{% extends 'users/base.html' %}
{% load static %}
{% load widget_tweaks %}
{% block content %}
    <div class="col mx-auto">
        <div class="auth-form-box">
            <div class="text-center mb-5">
                <a class="d-flex flex-center text-decoration-none mb-4"
                   href="{% url 'index' %}">
                    <div class="d-flex align-items-center fw-bolder fs-3 d-inline-block">
                        <img
                                src="{% static '/assets/img/icons/logo-iskane.png' %}" alt="phoenix" width="100"/>
                    </div>
                </a>
                <h3 class="text-body-highlight">Inscription</h3>
                <p class="text-body-tertiary">Créez votre compte pour commencer</p>
            </div>
            <form method="post" action="">
                {% csrf_token %}
                <div class="mb-3 text-start">
                    <label class="form-label" for="name">Nom d'utilisateur</label>
                    {% render_field form.username class="form-control" %}
                    {#                    <input class="form-control" id="name" type="text" placeholder="Name"/></div>#}
                </div>
                <div class="mb-3 text-start">
                    <label class="form-label" for="email">Email address</label>
                    {% render_field form.email class="form-control" %}
                    {#                    <input class="form-control" id="email" type="email" placeholder="name@example.com"/></div>#}
                </div>
                <div class="row g-3 mb-3">
                    <div class="col-xl-6">
                        <label class="form-label" for="password">Mot de passe</label>
                        {% render_field form.password1 class="form-control form-icon-input" %}
                        {#                        <input class="form-control form-icon-input" id="password" type="password" placeholder="Password"/>#}
                    </div>
                    <div class="col-xl-6">
                        <label class="form-label" for="confirmPassword">Confirmation</label>
                        {% render_field form.password2 class="form-control form-icon-input" %}
                        {#                        <input class="form-control form-icon-input" id="confirmPassword" type="password" placeholder="Confirm Password"/>#}
                    </div>
                </div>
                <!-- <div class="form-check mb-2">
                    <input class="form-check-input" id="termsService" type="checkbox"/>
                    <label class="form-label fs-9 text-transform-none" for="termsService">
                        I accept the <a href="#!">terms </a>and <a href="#!">privacy policy</a>
                    </label>
                </div> -->
                <button type="submit" class="btn btn-primary w-100 mb-3">Enregistrer</button>
                <div class="text-center">Vous avez déjà un compte ? <a class="fs-9 fw-bold"
                                                                       href="{% url 'auth:signin' %}">Connectez-vous</a>


                </div>
            </form>
        </div>
    </div>
{% endblock %}